### ISSUE TITLE
PureChat Extension dont work

### ISSUE THREAD

**Issue by MrBlasyMSK** [ShockedPlot7560/FactionMaster#123]
**Describe the bug**
When you start the server with the purechat version for FactionMaster, this error appears and does not let the server work.

**To Reproduce**
```
[12:24:17.064] [Server thread/INFO]: Enabling PureChat v2.0.0
[12:24:17.064] [Server thread/NOTICE]: [PureChat] No valid factions plugin in default-factions-plugin node was found. Disabling factions plugin support.
[12:24:17.065] [Server thread/CRITICAL]: ReflectionException: "Class "_64FF00\PurePerms\event\PPGroupChangedEvent" does not exist" (-1) in "pmsrc/src/plugin/PluginManager" at line 510
--- Stack trace ---
  #0 pmsrc/src/plugin/PluginManager(510): ReflectionClass->__construct(string[43] _64FF00\PurePerms\event\PPGroupChangedEvent)
  #1 pmsrc/src/plugin/PluginManager(532): pocketmine\plugin\PluginManager->getEventsHandledBy(object ReflectionMethod#112963)
  #2 plugins/PureChat_v2.0.0.phar/src/_64FF00/PureChat/PureChat(69): pocketmine\plugin\PluginManager->registerEvents(object _64FF00\PureChat\PCListener#113015, object _64FF00\PureChat\PureChat#24905)
  #3 pmsrc/src/plugin/PluginBase(137): _64FF00\PureChat\PureChat->onEnable()
  #4 pmsrc/src/plugin/PluginManager(437): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #5 pmsrc/src/Server(1385): pocketmine\plugin\PluginManager->enablePlugin(object _64FF00\PureChat\PureChat#24905)
  #6 pmsrc/src/Server(1011): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#24901)
  #7 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #8 pmsrc/src/PocketMine(327): pocketmine\server()
  #9 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
```

**Expected behavior**
Expect works

**Screenshots**
X

**System (please complete the following information):**
 - OS: Ubuntu
 - Version 
    * FactionMaster dev#214
    * PocketMine 4.2.3
    * Version of possible extension PureChat 2.0.0
 - PHP version 8.0
 - Plugin installed= X

**Additional context**
X

**Comment by ShockedPlot7560** [comment]
what did you enter in the default-faction configuration?

**Comment by MrBlasyMSK** [comment]
> what did you enter in the default-faction configuration?
```yml

# PureChat by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

---

# PureChat version string
# - string
version: "1.4.10-6"

# Set default factions plugin for PureChat
# - FactionMaster / null
default-factions-plugin: FactionMaster

# Enable this if you want to use per-world chat formats / per-world nametags for players
# - true / false
enable-multiworld-chat: false

# Please check if you have all PurePerms groups in your server here

# &0: Black, &1: Dark Blue, &2: Dark Green, &3: Dark Aqua, &4: Dark Red, &5: Dark Purple, &6: Gold, &7: Gray, &8: Dark Gray, &9: Blue
# &a: Green, &b: Aqua, &c: Red, &d: Light Purple, &e: Yellow, &f: White
# &k: Obfuscated, &l: Bold, &m: Strikethrough, &n: Underline, &o: Italic, &r: Reset

# Available PureChat tags: {display_name}, {msg}, {fac_name}, {fac_rank}, {prefix}, {suffix}, {world}
groups:
  Guest:
    chat: '&7[Guest] &f{fac_rank}{fac_name}&a {display_name} &7> &f{msg}'
    nametag: '&7[Guest] &f{display_name}'
    worlds: []
  Admin:
    chat: '&c[Admin] &7{fac_rank}{fac_name}&6 {display_name} &d>&b {msg}'
    nametag: '&a[Admin]&e {fac_rank}{fac_name} &6{display_name}'
    worlds: []
  Owner:
    chat: '&d[Owner] &c{fac_rank}{fac_name} &b{display_name} &c>&6> &b{msg}'
    nametag: '&d[Owner]&c {fac_rank}{fac_name} &b{display_name}'
    worlds: []
  OP:
    chat: '&a[OP] &5{fac_rank}{fac_name}&b {prefix}{display_name}{suffix} &c>&6> &f{msg}'
    nametag: '&a[OP] &c{fac_rank}{fac_name} &b{display_name}'
    worlds: []
...
```
