### ISSUE TITLE
Bug disappearing comments from config.yml

### ISSUE THREAD

**Issue by MrBlasyMSK** [ShockedPlot7560/FactionMaster#31]
If you start the server and go to the config, it will appear like this
```yml
---
PROVIDER: SQLITE
MYSQL_database:
  host: localhost
  name: FactionMaster
  user: root
  pass: ""
SQLITE_database:
  name: FactionMaster
banned-faction-name:
- op
- staff
- admin
- fuck
- shit
xp-win-per-kill: 1
power-win-per-kill: 2
power-loose-per-death: 2
faction-multiplicator: 2
allow-no-stuff: false
default-home-limit: 2
default-claim-limit: 2
default-member-limit: 2
default-ally-limit: 2
default-power: 0
min-faction-name-length: 3
max-faction-name-length: 20
active-image: false
faction-chat-active: false
faction-chat-symbol: $
faction-chat-message: '[{factionName}] {playerName}: {message}'
ally-chat-active: false
ally-chat-symbol: '%'
ally-chat-message: '[{factionName}] {playerName}: {message}'
broadcast-faction-create: false
broadcast-faction-create-message: '{playerName} has created the faction {factionName}'
broadcast-faction-delete: false
broadcast-faction-delete-message: '{playerName} has deleted the faction {factionName}'
broadcast-faction-transferProperty: false
broadcast-faction-transferProperty-message: '{playerName} transferred the property
  to {targetName} of the faction {factionName}'
claim-cost:
  type: power
  value: 200
claim-provider: flat
multiplication-factor: 2
decrease-factor: 100
allow-home-ennemy-claim: true
message-alert: true
message-alert-title: '{factionName}'
message-alert-subtitle: ""
message-alert-cooldown: 10
faction-scoreboard: false
faction-scoreboard-header: '- Top 10 faction -'
faction-scoreboard-lign: '{factionName}: Level {level}'
faction-scoreboard-position: 0|100|0|world
timeout-task: 60
sync-time: 200
...
```

PHP: 8.0.9
Pocketmine 3.22.4
FactionMaster: dev68
