### ISSUE TITLE
Button image dont work

### ISSUE THREAD

**Issue by MrBlasyMSK** [ShockedPlot7560/FactionMaster#39]
![image](https://user-images.githubusercontent.com/85447029/132568497-43c32786-7ef2-4697-83af-2c0c3cf1c017.png)
```yml
# If it set to true, image will be display near button
# If it set to false, image will be disabled
active-image: true
```
```yml
#This configuration file controls global resources used on your PocketMine-MP server.

#Choose whether players must use your chosen resource packs to join the server.
#NOTE: This will do nothing if there are no resource packs in the stack below.
force_resources: true
resource_stack:
  - FactionMaster.zip
  #Resource packs here are applied from bottom to top. This means that resources in higher packs will override those in lower packs.
  #Entries here must indicate the filename of the resource pack.
  #Example
  # - natural.zip
  # - vanilla.zip
  #If you want to force clients to use vanilla resources, you must place a vanilla resource pack in your resources folder and add it to the stack here.
```

Dev 74
